# Generated by Django 4.0.2 on 2022-10-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cgpa_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem1', models.FloatField()),
                ('sem2', models.FloatField()),
                ('sem3', models.FloatField()),
                ('sem4', models.FloatField()),
                ('sem5', models.FloatField()),
                ('sem6', models.FloatField()),
                ('sem7', models.FloatField()),
                ('sem8', models.FloatField()),
            ],
        ),
    ]
