# Generated by Django 4.0.2 on 2022-11-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksapp', '0002_sgpa_db_cgpa_db_usn_alter_cgpa_db_sem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgpa_db',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='usn',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
