# Generated by Django 4.1.2 on 2022-11-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksapp', '0003_sgpa_db_credit_sgpa_db_mark_sgpa_db_usn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgpa_db',
            old_name='credit',
            new_name='sem',
        ),
        migrations.RemoveField(
            model_name='sgpa_db',
            name='mark',
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='m9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sgpa_db',
            name='sgpa',
            field=models.FloatField(null=True),
        ),
    ]
